// <auto-generated />
using System;
using BallerupKommune.DAOs.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BallerupKommune.DAOs.Persistence.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250121093709_AddCommentDeclineInfoEntityToComment")]
    partial class AddCommentDeclineInfoEntityToComment
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.35")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("BallerupKommune.DAOs.Identity.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("longtext");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("longtext");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("BallerupKommune.DAOs.Identity.RefreshToken", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ApplicationUserId")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime>("ExpirationDate")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("IsRevoked")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Token")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("ApplicationUserId");

                    b.ToTable("RefreshTokens");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentDeclineInfoEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("DeclineReason")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("DeclinerInitials")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("CommentDeclineInfos");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommentDeclineInfoId")
                        .HasColumnType("int");

                    b.Property<int?>("CommentParrentId")
                        .HasColumnType("int");

                    b.Property<int>("CommentStatusId")
                        .HasColumnType("int");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("ConsentId")
                        .HasColumnType("int");

                    b.Property<bool>("ContainsSensitiveInformation")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<string>("OnBehalfOf")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentDeclineInfoId");

                    b.HasIndex("CommentParrentId");

                    b.HasIndex("CommentStatusId");

                    b.HasIndex("CommentTypeId");

                    b.HasIndex("ConsentId")
                        .IsUnique();

                    b.HasIndex("HearingId");

                    b.HasIndex("UserId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CommentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentTypeId");

                    b.ToTable("CommentStatuses");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CommentTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CompanyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cvr")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.HasKey("Id");

                    b.ToTable("Companies");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CompanyHearingRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingId")
                        .HasColumnType("int");

                    b.Property<int>("HearingRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HearingId");

                    b.HasIndex("HearingRoleId");

                    b.ToTable("CompanyHearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ConsentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("GlobalContentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("GlobalContentId");

                    b.ToTable("Consents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("FieldId")
                        .HasColumnType("int");

                    b.Property<string>("FileContentType")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("FileName")
                        .HasMaxLength(300)
                        .HasColumnType("varchar(300)");

                    b.Property<string>("FilePath")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("HearingId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("TextContent")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("FieldId");

                    b.HasIndex("HearingId");

                    b.ToTable("Contents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ContentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ContentTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("AllowTemplates")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("int");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<int>("HearingTemplateId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("ValidationRuleId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FieldTypeId");

                    b.HasIndex("HearingTemplateId");

                    b.HasIndex("ValidationRuleId")
                        .IsUnique();

                    b.ToTable("Fields");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FieldId")
                        .HasColumnType("int");

                    b.Property<int>("HearingTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Text")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("FieldId");

                    b.HasIndex("HearingTypeId");

                    b.ToTable("FieldTemplates");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("FieldTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTypeSpecificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("ContentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FieldTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("ContentTypeId");

                    b.HasIndex("FieldTypeId");

                    b.ToTable("FieldTypeSpecifications");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.GlobalContentEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("GlobalContentTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Version")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("GlobalContentTypeId");

                    b.ToTable("GlobalContents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.GlobalContentTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("GlobalContentTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("ClosedHearing")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("ContactPersonDepartmentName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPersonEmail")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPersonName")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("ContactPersonPhoneNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("Deadline")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("EsdhMetaData")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EsdhNumber")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("EsdhTitle")
                        .HasMaxLength(110)
                        .HasColumnType("varchar(110)");

                    b.Property<int?>("HearingStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("HearingTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("JournalizedStatusId")
                        .HasColumnType("int");

                    b.Property<int?>("KleHierarchyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("ShowComments")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("SubjectAreaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HearingStatusId");

                    b.HasIndex("HearingTypeId");

                    b.HasIndex("JournalizedStatusId");

                    b.HasIndex("KleHierarchyId");

                    b.HasIndex("SubjectAreaId");

                    b.ToTable("Hearings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Role")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("HearingStatus");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("HearingTemplates");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingTemplateId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsInternalHearing")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("HearingTemplateId");

                    b.ToTable("HearingTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.JournalizedStatusEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("JournalizedStatuses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Created = new DateTime(2024, 3, 20, 15, 48, 56, 396, DateTimeKind.Local),
                            Status = 0
                        },
                        new
                        {
                            Id = 2,
                            Created = new DateTime(2024, 3, 20, 15, 48, 56, 396, DateTimeKind.Local),
                            Status = 1
                        },
                        new
                        {
                            Id = 3,
                            Created = new DateTime(2024, 3, 20, 15, 48, 56, 396, DateTimeKind.Local),
                            Status = 2
                        });
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.KleHierarchyEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int?>("KleHierarchyParrentId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Number")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("KleHierarchyParrentId");

                    b.ToTable("KleHierarchies");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.KleMappingEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingTypeId")
                        .HasColumnType("int");

                    b.Property<int>("KleHierarchyId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("HearingTypeId");

                    b.HasIndex("KleHierarchyId");

                    b.ToTable("KleMappings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CommentId")
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingId")
                        .HasColumnType("int");

                    b.Property<bool>("IsSendToQueue")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("NotificationQueueId")
                        .HasColumnType("int");

                    b.Property<int>("NotificationTypeId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CommentId");

                    b.HasIndex("CompanyId");

                    b.HasIndex("HearingId");

                    b.HasIndex("NotificationQueueId");

                    b.HasIndex("NotificationTypeId");

                    b.HasIndex("UserId");

                    b.ToTable("Notifications");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationQueueEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("ErrorTexts")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<bool>("IsSend")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("MessageChannel")
                        .HasColumnType("int");

                    b.Property<string>("RecipientAddress")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int>("RetryCount")
                        .HasColumnType("int");

                    b.Property<string>("Subject")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<DateTime?>("SuccessfullSendDate")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.ToTable("NotificationQueues");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationTemplateEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("NotificationTemplateText")
                        .HasMaxLength(1000)
                        .HasColumnType("varchar(1000)");

                    b.Property<string>("SubjectTemplate")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("NotificationTemplates");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationTypeEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("Frequency")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("NotificationTemplateId")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("NotificationTemplateId")
                        .IsUnique();

                    b.ToTable("NotificationTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.SubjectAreaEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.HasKey("Id");

                    b.ToTable("SubjectAreas");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserCapacityEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("Capacity")
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.HasKey("Id");

                    b.ToTable("UserCapacities");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int?>("CompanyId")
                        .HasColumnType("int");

                    b.Property<string>("Cpr")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Cvr")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Email")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("EmployeeDisplayName")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("Identifier")
                        .HasMaxLength(100)
                        .HasColumnType("varchar(100)");

                    b.Property<bool>("IsAdministrator")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsHearingCreator")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Name")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<string>("PersonalIdentifier")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<int?>("UserCapacityId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CompanyId");

                    b.HasIndex("UserCapacityId");

                    b.ToTable("UsersDb");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserHearingRoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("HearingId")
                        .HasColumnType("int");

                    b.Property<int>("HearingRoleId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HearingId");

                    b.HasIndex("HearingRoleId");

                    b.HasIndex("UserId");

                    b.ToTable("UserHearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ValidationRuleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("AllowedFileTypes")
                        .HasMaxLength(500)
                        .HasColumnType("varchar(500)");

                    b.Property<bool?>("CanBeEmpty")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("Created")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int>("FieldType")
                        .HasColumnType("int");

                    b.Property<DateTime?>("LastModified")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("LastModifiedBy")
                        .HasMaxLength(50)
                        .HasColumnType("varchar(50)");

                    b.Property<int?>("MaxFileCount")
                        .HasColumnType("int");

                    b.Property<int?>("MaxFileSize")
                        .HasColumnType("int");

                    b.Property<int?>("MaxLength")
                        .HasColumnType("int");

                    b.Property<int?>("MinLength")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ValidationRules");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("ClaimType")
                        .HasColumnType("longtext");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("RoleId")
                        .HasColumnType("varchar(255)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Name")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("BallerupKommune.DAOs.Identity.RefreshToken", b =>
                {
                    b.HasOne("BallerupKommune.DAOs.Identity.ApplicationUser", "ApplicationUser")
                        .WithMany("RefreshTokens")
                        .HasForeignKey("ApplicationUserId");

                    b.Navigation("ApplicationUser");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CommentDeclineInfoEntity", "CommentDeclineInfo")
                        .WithMany()
                        .HasForeignKey("CommentDeclineInfoId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("BallerupKommune.Entities.Entities.CommentEntity", "CommentParrent")
                        .WithMany("CommentChildren")
                        .HasForeignKey("CommentParrentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BallerupKommune.Entities.Entities.CommentStatusEntity", "CommentStatus")
                        .WithMany("Comments")
                        .HasForeignKey("CommentStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.CommentTypeEntity", "CommentType")
                        .WithMany("Comments")
                        .HasForeignKey("CommentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.ConsentEntity", "Consent")
                        .WithOne("Comment")
                        .HasForeignKey("BallerupKommune.Entities.Entities.CommentEntity", "ConsentId");

                    b.HasOne("BallerupKommune.Entities.Entities.HearingEntity", "Hearing")
                        .WithMany("Comments")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentDeclineInfo");

                    b.Navigation("CommentParrent");

                    b.Navigation("CommentStatus");

                    b.Navigation("CommentType");

                    b.Navigation("Consent");

                    b.Navigation("Hearing");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentStatusEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CommentTypeEntity", "CommentType")
                        .WithMany("CommentStatuses")
                        .HasForeignKey("CommentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CommentType");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CompanyHearingRoleEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CompanyEntity", "Company")
                        .WithMany("CompanyHearingRoles")
                        .HasForeignKey("CompanyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.HearingEntity", "Hearing")
                        .WithMany("CompanyHearingRoles")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.HearingRoleEntity", "HearingRole")
                        .WithMany("CompanyHearingRoles")
                        .HasForeignKey("HearingRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Company");

                    b.Navigation("Hearing");

                    b.Navigation("HearingRole");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ConsentEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.GlobalContentEntity", "GlobalContent")
                        .WithMany("Consents")
                        .HasForeignKey("GlobalContentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalContent");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ContentEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CommentEntity", "Comment")
                        .WithMany("Contents")
                        .HasForeignKey("CommentId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BallerupKommune.Entities.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("Contents")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.FieldEntity", "Field")
                        .WithMany("Contents")
                        .HasForeignKey("FieldId");

                    b.HasOne("BallerupKommune.Entities.Entities.HearingEntity", "Hearing")
                        .WithMany("Contents")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Comment");

                    b.Navigation("ContentType");

                    b.Navigation("Field");

                    b.Navigation("Hearing");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.FieldTypeEntity", "FieldType")
                        .WithMany("Fields")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.HearingTemplateEntity", "HearingTemplate")
                        .WithMany("Fields")
                        .HasForeignKey("HearingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.ValidationRuleEntity", "ValidationRule")
                        .WithOne("Field")
                        .HasForeignKey("BallerupKommune.Entities.Entities.FieldEntity", "ValidationRuleId");

                    b.Navigation("FieldType");

                    b.Navigation("HearingTemplate");

                    b.Navigation("ValidationRule");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTemplateEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.FieldEntity", "Field")
                        .WithMany("FieldTemplates")
                        .HasForeignKey("FieldId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.HearingTypeEntity", "HearingType")
                        .WithMany("FieldTemplates")
                        .HasForeignKey("HearingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Field");

                    b.Navigation("HearingType");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTypeSpecificationEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.ContentTypeEntity", "ContentType")
                        .WithMany("FieldTypeSpecifications")
                        .HasForeignKey("ContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.FieldTypeEntity", "FieldType")
                        .WithMany("FieldTypeSpecifications")
                        .HasForeignKey("FieldTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ContentType");

                    b.Navigation("FieldType");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.GlobalContentEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.GlobalContentTypeEntity", "GlobalContentType")
                        .WithMany("GlobalContents")
                        .HasForeignKey("GlobalContentTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("GlobalContentType");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.HearingStatusEntity", "HearingStatus")
                        .WithMany("Hearings")
                        .HasForeignKey("HearingStatusId");

                    b.HasOne("BallerupKommune.Entities.Entities.HearingTypeEntity", "HearingType")
                        .WithMany("Hearings")
                        .HasForeignKey("HearingTypeId");

                    b.HasOne("BallerupKommune.Entities.Entities.JournalizedStatusEntity", "JournalizedStatus")
                        .WithMany("Hearings")
                        .HasForeignKey("JournalizedStatusId");

                    b.HasOne("BallerupKommune.Entities.Entities.KleHierarchyEntity", "KleHierarchy")
                        .WithMany("Hearings")
                        .HasForeignKey("KleHierarchyId");

                    b.HasOne("BallerupKommune.Entities.Entities.SubjectAreaEntity", "SubjectArea")
                        .WithMany("Hearings")
                        .HasForeignKey("SubjectAreaId");

                    b.Navigation("HearingStatus");

                    b.Navigation("HearingType");

                    b.Navigation("JournalizedStatus");

                    b.Navigation("KleHierarchy");

                    b.Navigation("SubjectArea");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingTypeEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.HearingTemplateEntity", "HearingTemplate")
                        .WithMany("HearingTypes")
                        .HasForeignKey("HearingTemplateId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HearingTemplate");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.KleHierarchyEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.KleHierarchyEntity", "KleHierarchyParrent")
                        .WithMany("KleHierarchyChildren")
                        .HasForeignKey("KleHierarchyParrentId");

                    b.Navigation("KleHierarchyParrent");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.KleMappingEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.HearingTypeEntity", "HearingType")
                        .WithMany("KleMappings")
                        .HasForeignKey("HearingTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.KleHierarchyEntity", "KleHierarchy")
                        .WithMany("KleMappings")
                        .HasForeignKey("KleHierarchyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HearingType");

                    b.Navigation("KleHierarchy");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CommentEntity", "Comment")
                        .WithMany()
                        .HasForeignKey("CommentId");

                    b.HasOne("BallerupKommune.Entities.Entities.CompanyEntity", "Company")
                        .WithMany("Notifications")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BallerupKommune.Entities.Entities.HearingEntity", "Hearing")
                        .WithMany("Notifications")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.NotificationQueueEntity", "NotificationQueue")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationQueueId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BallerupKommune.Entities.Entities.NotificationTypeEntity", "NotificationType")
                        .WithMany("Notifications")
                        .HasForeignKey("NotificationTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.UserEntity", "User")
                        .WithMany("Notifications")
                        .HasForeignKey("UserId");

                    b.Navigation("Comment");

                    b.Navigation("Company");

                    b.Navigation("Hearing");

                    b.Navigation("NotificationQueue");

                    b.Navigation("NotificationType");

                    b.Navigation("User");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationTypeEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.NotificationTemplateEntity", "NotificationTemplate")
                        .WithOne("NotificationType")
                        .HasForeignKey("BallerupKommune.Entities.Entities.NotificationTypeEntity", "NotificationTemplateId");

                    b.Navigation("NotificationTemplate");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.CompanyEntity", "Company")
                        .WithMany("Users")
                        .HasForeignKey("CompanyId");

                    b.HasOne("BallerupKommune.Entities.Entities.UserCapacityEntity", "UserCapacity")
                        .WithMany("Users")
                        .HasForeignKey("UserCapacityId");

                    b.Navigation("Company");

                    b.Navigation("UserCapacity");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserHearingRoleEntity", b =>
                {
                    b.HasOne("BallerupKommune.Entities.Entities.HearingEntity", "Hearing")
                        .WithMany("UserHearingRoles")
                        .HasForeignKey("HearingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.HearingRoleEntity", "HearingRole")
                        .WithMany("UserHearingRoles")
                        .HasForeignKey("HearingRoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.Entities.Entities.UserEntity", "User")
                        .WithMany("UserHearingRoles")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hearing");

                    b.Navigation("HearingRole");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("BallerupKommune.DAOs.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("BallerupKommune.DAOs.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("BallerupKommune.DAOs.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("BallerupKommune.DAOs.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("BallerupKommune.DAOs.Identity.ApplicationUser", b =>
                {
                    b.Navigation("RefreshTokens");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentEntity", b =>
                {
                    b.Navigation("CommentChildren");

                    b.Navigation("Contents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentStatusEntity", b =>
                {
                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CommentTypeEntity", b =>
                {
                    b.Navigation("CommentStatuses");

                    b.Navigation("Comments");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.CompanyEntity", b =>
                {
                    b.Navigation("CompanyHearingRoles");

                    b.Navigation("Notifications");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ConsentEntity", b =>
                {
                    b.Navigation("Comment");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ContentTypeEntity", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("FieldTypeSpecifications");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldEntity", b =>
                {
                    b.Navigation("Contents");

                    b.Navigation("FieldTemplates");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.FieldTypeEntity", b =>
                {
                    b.Navigation("FieldTypeSpecifications");

                    b.Navigation("Fields");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.GlobalContentEntity", b =>
                {
                    b.Navigation("Consents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.GlobalContentTypeEntity", b =>
                {
                    b.Navigation("GlobalContents");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("CompanyHearingRoles");

                    b.Navigation("Contents");

                    b.Navigation("Notifications");

                    b.Navigation("UserHearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingRoleEntity", b =>
                {
                    b.Navigation("CompanyHearingRoles");

                    b.Navigation("UserHearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingStatusEntity", b =>
                {
                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingTemplateEntity", b =>
                {
                    b.Navigation("Fields");

                    b.Navigation("HearingTypes");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.HearingTypeEntity", b =>
                {
                    b.Navigation("FieldTemplates");

                    b.Navigation("Hearings");

                    b.Navigation("KleMappings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.JournalizedStatusEntity", b =>
                {
                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.KleHierarchyEntity", b =>
                {
                    b.Navigation("Hearings");

                    b.Navigation("KleHierarchyChildren");

                    b.Navigation("KleMappings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationQueueEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationTemplateEntity", b =>
                {
                    b.Navigation("NotificationType");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.NotificationTypeEntity", b =>
                {
                    b.Navigation("Notifications");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.SubjectAreaEntity", b =>
                {
                    b.Navigation("Hearings");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserCapacityEntity", b =>
                {
                    b.Navigation("Users");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.UserEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Notifications");

                    b.Navigation("UserHearingRoles");
                });

            modelBuilder.Entity("BallerupKommune.Entities.Entities.ValidationRuleEntity", b =>
                {
                    b.Navigation("Field");
                });
#pragma warning restore 612, 618
        }
    }
}
