namespace Agora.DAOs.UserDataEnrichment.CVR.DTOs;
/**
 * NOTE: THIS FILE IS AUTOGENERATED BASED ON THE JSON RESPONSE FROM THE DATAFORDELER HENTCVRDATA ENDPOINT
 * THE FOLLOWING TOOL WAS USED TO GENERATED THIS CLASS: https://codebeautify.org/json-to-csharp-pojo-generator
 * UNUSED ATTRIBUTES WERE REMOVED FOR BREVITY
 */

using Newtonsoft.Json;
using Newtonsoft.Json.Converters;
using System;
using System.Globalization;

public partial class HentCvrDataDto
{
    [JsonProperty("virksomhed")]
    public Virksomhed Virksomhed { get; set; }

    [JsonProperty("virksomhedsnavn")]
    public VirksomhedsNavn VirksomhedsNavn { get; set; }

    [JsonProperty("beliggenhedsadresse")]
    public AddressDto Beliggenhedsadresse { get; set; }

    [JsonProperty("postadresse")]
    public AddressDto Postadresse { get; set; }
}

public class VirksomhedsNavn
{
    [JsonProperty("vaerdi")]
    public string Navn { get; set; }

    [JsonProperty("registreringFra")]
    public string RegistreringFra { get; set; }

    [JsonProperty("registreringTil")]
    public string RegistreringTil { get; set; }

    [JsonProperty("registreringsaktoer")]
    public string Registreringsaktoer { get; set; }

    [JsonProperty("virkningFra")]
    public DateTimeOffset VirkningFra { get; set; }

    [JsonProperty("virkningTil")]
    public string VirkningTil { get; set; }

    [JsonProperty("virkningsaktoer")]
    public string Virkningsaktoer { get; set; }

    [JsonProperty("metadata")]
    public Metadata Metadata { get; set; }
}

public class AddressDto
{
    [JsonProperty("adresse")]
    public Guid Adresse { get; set; }

    [JsonProperty("CVRAdresse_vejkode")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long CvrAdresseVejkode { get; set; }

    [JsonProperty("CVRAdresse_husnummerFra")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long CvrAdresseHusnummerFra { get; set; }

    [JsonProperty("CVRAdresse_etagebetegnelse")]
    public string CvrAdresseEtagebetegnelse { get; set; }

    [JsonProperty("CVRAdresse_doerbetegnelse")]
    public string CvrAdresseDoerbetegnelse { get; set; }

    [JsonProperty("CVRAdresse_kommunekode")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long CvrAdresseKommunekode { get; set; }

    [JsonProperty("CVRAdresse_kommunenavn")]
    public string CvrAdresseKommunenavn { get; set; }

    [JsonProperty("CVRAdresse_postdistrikt")]
    public string CvrAdressePostdistrikt { get; set; }

    [JsonProperty("CVRAdresse_vejnavn")]
    public string CvrAdresseVejnavn { get; set; }

    [JsonProperty("CVRAdresse_postnummer")]
    [JsonConverter(typeof(ParseStringConverter))]
    public long CvrAdressePostnummer { get; set; }

    [JsonProperty("CVRAdresse_supplerendeBynavn")]
    public string CvrAdresseSupplerendeBynavn { get; set; }

    [JsonProperty("CVRAdresse_adresseFritekst")]
    public string CvrAdresseAdresseFritekst { get; set; }

    [JsonProperty("CVRAdresse_landekode")]
    public string CvrAdresseLandekode { get; set; }

    [JsonProperty("CVRAdresse_postboks")]
    public string CvrAdressePostboks { get; set; }

    [JsonProperty("coNavn")]
    public string CoNavn { get; set; }

    [JsonProperty("registreringFra")]
    public string RegistreringFra { get; set; }

    [JsonProperty("registreringTil")]
    public string RegistreringTil { get; set; }

    [JsonProperty("registreringsaktoer")]
    public string Registreringsaktoer { get; set; }

    [JsonProperty("virkningFra")]
    public DateTimeOffset VirkningFra { get; set; }

    [JsonProperty("virkningTil")]
    public string VirkningTil { get; set; }

    [JsonProperty("virkningsaktoer")]
    public string Virkningsaktoer { get; set; }

    [JsonProperty("metadata")]
    public Metadata Metadata { get; set; }
}

public class Metadata
{
    [JsonProperty("datafordelerOpdateringstid")]
    public string DatafordelerOpdateringstid { get; set; }
}

public class Virksomhed
{
    [JsonProperty("Id")]
    public string Id { get; set; }

    [JsonProperty("CVRNummer")]
    public long CvrNummer { get; set; }

    [JsonProperty("virksomhedStartdato")]
    public DateTimeOffset VirksomhedStartdato { get; set; }

    [JsonProperty("registreringFra")]
    public string RegistreringFra { get; set; }

    [JsonProperty("registreringsaktoer")]
    public string Registreringsaktoer { get; set; }

    [JsonProperty("virkningFra")]
    public DateTimeOffset VirkningFra { get; set; }

    [JsonProperty("virkningsaktoer")]
    public string Virkningsaktoer { get; set; }

    [JsonProperty("status")]
    public string Status { get; set; }

    [JsonProperty("metadata")]
    public Metadata Metadata { get; set; }
}

public partial class HentCvrDataDto
{
    public static HentCvrDataDto FromJson(string json) => JsonConvert.DeserializeObject<HentCvrDataDto>(json, Converter.Settings);
}

public static class Serialize
{
    public static string ToJson(this HentCvrDataDto self) => JsonConvert.SerializeObject(self, Converter.Settings);
}

internal static class Converter
{
    public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
    {
        MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
        DateParseHandling = DateParseHandling.None,
        Converters =
            {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
    };
}

internal class ParseStringConverter : JsonConverter
{
    public override bool CanConvert(Type t) => t == typeof(long) || t == typeof(long?);

    public override object ReadJson(JsonReader reader, Type t, object existingValue, JsonSerializer serializer)
    {
        if (reader.TokenType == JsonToken.Null) return null;
        var value = serializer.Deserialize<string>(reader);
        long l;
        if (Int64.TryParse(value, out l))
        {
            return l;
        }
        throw new Exception("Cannot unmarshal type long");
    }

    public override void WriteJson(JsonWriter writer, object untypedValue, JsonSerializer serializer)
    {
        if (untypedValue == null)
        {
            serializer.Serialize(writer, null);
            return;
        }
        var value = (long)untypedValue;
        serializer.Serialize(writer, value.ToString());
        return;
    }

    public static readonly ParseStringConverter Singleton = new ParseStringConverter();
}
